#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 1、当系统环境变量中不存在 NSMS_ACTIVE 时，加载后缀为dev的文件（application-dev.properties），否则加载系统环境变量中的配置文件
# 2、如 在测试环境中可 export NSMS_ACTIVE=sit
# 3、一般建议包含如下文件：
#        开发环境（dev）                    application-dev.properties
#        集成测试（sit）                    application-sit.properties
#        用户验收测试（uat)     application-uat.properties
#        生产环境（prod）                  application-prod.properties
# 4、也可指定启动方式：java -jar nsms-gateway.jar --spring.profiles.active=uat 指定 UAT环境的配置文件
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
spring: 
 profiles: 
  active: ${NSMS_ACTIVE:dev}